import type { Metadata } from "next";
import LegalPage from "../../components/LegalPage";

export const metadata: Metadata = { title: "Política de Privacidad | VetConver", description: "Cómo VetConver trata y protege los datos de sus usuarios." };

export default function PrivacyPage() {
  return <LegalPage eyebrow="PROTECCIÓN DE DATOS" title="Política de Privacidad" updated="29 de septiembre de 2026">
    <section><h2>1. Responsable y contacto</h2><p>El responsable de VetConver y del tratamiento de los datos asociados al servicio es Hilario Sondón. Las consultas y solicitudes relacionadas con privacidad pueden realizarse por WhatsApp al 2244-429316. Antes de responder solicitudes sobre una cuenta podrá requerirse acreditación de identidad.</p></section>
    <section><h2>2. Datos tratados</h2><p>Según el tipo de cuenta y las funciones utilizadas, VetConver puede tratar:</p><ul><li>nombre, correo electrónico o nombre de usuario, credenciales administradas por Firebase Authentication, rol y estado de acceso;</li><li>información de suscripción, medio y estado de pago; VetConver no almacena datos completos de tarjetas;</li><li>nombre, código, domicilio, contacto, logo, directores técnicos, diagnósticos, técnicas, reactivos y conclusiones configuradas por cada laboratorio;</li><li>nombres y CUIT de veterinarios guardados por el laboratorio;</li><li>datos contenidos en actas y protocolos, como productor, establecimiento, RENSPA, muestras, identificaciones, categorías, fechas, resultados y observaciones;</li><li>datos técnicos mínimos de navegación, un identificador aleatorio de visitante, fuente de acceso y eventos agregados de uso.</li></ul></section>
    <section><h2>3. Finalidades</h2><p>Los datos se utilizan para autenticar usuarios, habilitar funciones, mantener configuraciones por cuenta, interpretar documentos, generar archivos solicitados, administrar pagos y accesos, brindar soporte, prevenir abusos, corregir errores y conocer de manera agregada el uso del servicio.</p><p>VetConver no utiliza el contenido de actas, protocolos o resultados para publicidad ni lo comercializa.</p></section>
    <section><h2>4. Tratamiento de actas y archivos</h2><p>Cuando un laboratorio adjunta un PDF, el archivo se transmite al servidor para extraer su texto y estructura. VetConver no lo guarda intencionalmente en una biblioteca o historial: el contenido procesado se devuelve a la sesión activa. Los JSON, PDF y Excel se generan para su descarga y permanecen bajo control del usuario en su dispositivo.</p><p>La configuración de “Mis datos” sí se conserva en Firebase, separada por el identificador único de cada cuenta. El sistema utiliza controles de acceso para impedir que un laboratorio consulte la configuración de otro.</p></section>
    <section><h2>5. Proveedores y transferencias</h2><p>Para operar el servicio se utilizan proveedores tecnológicos, entre ellos Firebase/Google para autenticación y base de datos, Vercel para alojamiento y ejecución, servicios de correo para comunicaciones y Mercado Pago cuando corresponda. Estos proveedores pueden procesar información desde infraestructura ubicada fuera de Argentina, conforme a sus condiciones, medidas de seguridad y mecanismos legales aplicables.</p><p>Solo se comparte con cada proveedor la información necesaria para la función que presta. También podrá comunicarse información cuando exista una obligación legal o requerimiento válido de una autoridad competente.</p></section>
    <section><h2>6. Seguridad y separación de cuentas</h2><p>VetConver aplica autenticación, reglas de acceso por usuario, validaciones del lado del servidor y separación de configuraciones por UID. Las cuentas autenticadas de laboratorio esperan la carga de su propio perfil y no reutilizan configuraciones locales de otras cuentas.</p><p>Ningún sistema puede garantizar seguridad absoluta. Los usuarios deben proteger sus credenciales, cerrar sesión en dispositivos compartidos y comunicar inmediatamente cualquier acceso o comportamiento sospechoso.</p></section>
    <section><h2>7. Conservación</h2><p>Los datos de cuenta y configuración se conservan mientras el acceso esté vigente y posteriormente durante el tiempo razonablemente necesario para administrar la relación, resolver incidencias y cumplir obligaciones legales o contables. Los datos que dejen de ser necesarios serán eliminados, anonimizados o archivados según corresponda.</p><p>Las métricas de visitas y eventos se conservan principalmente de forma agregada. Los archivos descargados por el usuario quedan sujetos a las políticas y copias de seguridad de su propio dispositivo.</p></section>
    <section><h2>8. Derechos de las personas</h2><p>Las personas titulares pueden solicitar información, acceso, rectificación, actualización o supresión de sus datos, conforme a la Ley 25.326, mediante el canal de contacto indicado. Algunas solicitudes podrán limitarse cuando exista una obligación legal de conservación o cuando la información sea necesaria para ejercer o defender derechos.</p><p>La Agencia de Acceso a la Información Pública, en su carácter de órgano de control de la Ley 25.326, recibe denuncias y reclamos relacionados con la protección de datos personales.</p></section>
    <section><h2>9. Datos de terceros</h2><p>Cuando un usuario incorpora datos de productores, veterinarios, titulares, establecimientos u otras personas, declara contar con autorización, relación profesional o base legítima suficiente para tratarlos. Debe limitar la carga a lo necesario para la tarea y respetar las obligaciones de confidencialidad propias de su actividad.</p></section>
    <section><h2>10. Almacenamiento local y tecnologías similares</h2><p>VetConver puede utilizar almacenamiento local o de sesión para autenticación, seguridad, preferencias esenciales, identificación anónima de visitas y funcionamiento técnico. Las cuentas de laboratorio autenticadas no utilizan ese almacenamiento para compartir o recuperar la configuración privada de otros laboratorios.</p></section>
    <section><h2>11. Cambios en esta política</h2><p>Esta política podrá actualizarse cuando cambien el servicio, los proveedores o la normativa. La fecha y versión vigentes se publicarán en esta página y los cambios sustanciales serán informados por medios razonables.</p></section>
  </LegalPage>;
}
