import type { Metadata } from "next";
import LegalPage from "../../components/LegalPage";

export const metadata: Metadata = { title: "Términos y Condiciones | VetConver", description: "Condiciones de uso de VetConver para veterinarios y laboratorios." };

export default function TermsPage() {
  return <LegalPage eyebrow="CONDICIONES DEL SERVICIO" title="Términos y Condiciones" updated="29 de septiembre de 2026">
    <section><h2>1. Identificación y alcance</h2><p>VetConver es una herramienta digital independiente desarrollada y administrada por Hilario Sondón, destinada a simplificar tareas administrativas de veterinarios y laboratorios veterinarios. Para consultas relacionadas con el servicio, el canal de contacto es WhatsApp al 2244-429316.</p><p>Estos términos regulan el registro, acceso y uso del sitio, sus módulos y los archivos que genera. Al registrarse, acceder o utilizar VetConver, la persona usuaria declara haber leído y aceptado estos Términos y la <a href="/privacidad">Política de Privacidad</a>.</p></section>
    <section><h2>2. Naturaleza de la herramienta</h2><p>VetConver facilita la preparación de planillas compatibles con SIGATM y, para laboratorios habilitados, la lectura de actas PDF, preparación de protocolos y generación de archivos JSON, PDF y Excel. Es una herramienta complementaria y de asistencia administrativa.</p><p>VetConver no pertenece, representa ni se encuentra afiliado a SENASA, SIGATM o GRECERT. Tampoco reemplaza esos sistemas, las constancias oficiales, el criterio profesional, los procedimientos internos del laboratorio ni las obligaciones regulatorias aplicables.</p></section>
    <section><h2>3. Cuentas y acceso</h2><ul><li>La información suministrada debe ser exacta, actual y completa.</li><li>Las credenciales son personales. La persona usuaria debe proteger su contraseña y comunicar cualquier acceso no autorizado.</li><li>Los accesos de laboratorio pueden ser creados, configurados, habilitados, suspendidos o deshabilitados administrativamente.</li><li>No se permite utilizar VetConver con fines ilícitos, alterar su funcionamiento, intentar acceder a cuentas ajenas ni eludir medidas de seguridad.</li></ul></section>
    <section><h2>4. Responsabilidad de veterinarios y laboratorios</h2><p>La persona usuaria es responsable de los datos que ingresa, copia, importa, selecciona, modifica o confirma. En particular, el laboratorio debe revisar antes de descargar, presentar, adjuntar o utilizar cualquier archivo:</p><ul><li>número de acta y protocolo, fechas, RENSPA, identificación y categoría de las muestras;</li><li>diagnóstico, técnica, códigos, reactivos, lotes, vencimientos, estampillas y resultados;</li><li>datos del laboratorio, director técnico, veterinario interviniente y conclusiones;</li><li>correspondencia entre el archivo generado, el acta original y el trabajo efectivamente realizado.</li></ul><p>La descarga de un archivo no implica que VetConver certifique su exactitud, validez oficial o aceptación por GRECERT/SENASA. La decisión final de utilizarlo y la obligación de efectuar el control profesional corresponden al usuario y, cuando corresponda, al laboratorio y su dirección técnica.</p></section>
    <section><h2>5. Archivos generados y errores de origen</h2><p>VetConver procesa información aportada por el usuario o contenida en documentos externos. La calidad del resultado depende de la legibilidad, estructura y exactitud de esa información. La persona usuaria debe corregir cualquier inconsistencia advertida por el sistema y verificar también posibles errores que no hayan sido detectados automáticamente.</p><p>VetConver no responde por errores derivados de actas incompletas, PDFs dañados o con formatos modificados, datos incorrectos, configuraciones erróneas del laboratorio, selección equivocada de resultados o técnicas, omisión de controles, manipulación posterior de archivos o uso contrario a estas condiciones.</p></section>
    <section><h2>6. Cambios en sistemas oficiales</h2><p>SIGATM, GRECERT, SENASA y sus formatos pueden modificarse sin intervención de VetConver. Ante cambios, incompatibilidades o rechazos, el usuario deberá suspender la utilización del archivo afectado, verificar la información y comunicar la situación. VetConver podrá bloquear temporalmente una función para prevenir resultados incorrectos.</p></section>
    <section><h2>7. Disponibilidad y servicios de terceros</h2><p>Se procura mantener el servicio disponible y actualizado, pero no se garantiza un funcionamiento ininterrumpido. Pueden producirse tareas de mantenimiento, problemas de conectividad o interrupciones de proveedores como Firebase, Vercel, servicios de correo, Mercado Pago u otros servicios necesarios.</p></section>
    <section><h2>8. Planes, pagos y cancelaciones</h2><p>Los planes, pruebas y modalidades de pago serán los informados al usuario al momento de contratar o acordar el alta. Los laboratorios pueden tener una modalidad administrada personalmente y facturada por fuera de la plataforma. La falta de pago, vencimiento o incumplimiento podrá ocasionar la suspensión del acceso, sin eliminar automáticamente la cuenta.</p></section>
    <section><h2>9. Propiedad intelectual</h2><p>El software, diseño, marca, textos, estructura, validaciones y demás componentes propios de VetConver se encuentran protegidos. El acceso al servicio no transfiere derechos de propiedad ni autoriza su copia, ingeniería inversa, distribución, reventa o explotación fuera del uso contratado.</p></section>
    <section><h2>10. Limitación razonable de responsabilidad</h2><p>En la máxima medida permitida por la normativa aplicable, VetConver no será responsable por decisiones profesionales o administrativas tomadas por el usuario, cargas realizadas sin revisión, rechazos de sistemas oficiales, pérdida de oportunidades, sanciones derivadas de información incorrecta aportada o confirmada por el usuario, ni daños indirectos originados en un uso inadecuado del servicio.</p><p>Nada de lo aquí indicado excluye responsabilidades que no puedan ser válidamente limitadas conforme a la legislación argentina, ni restringe derechos irrenunciables que pudieran corresponder.</p></section>
    <section><h2>11. Suspensión y finalización</h2><p>VetConver podrá suspender o cancelar accesos ante incumplimientos, riesgos de seguridad, uso abusivo, falta de pago o utilización que pueda afectar a terceros o al funcionamiento del servicio. La persona usuaria puede solicitar la baja y eliminación de su cuenta por el canal de contacto.</p></section>
    <section><h2>12. Modificaciones y legislación aplicable</h2><p>Estos términos podrán actualizarse cuando cambien el servicio, la normativa o los proveedores. La versión vigente estará siempre publicada en esta página. Los cambios sustanciales serán comunicados por medios razonables.</p><p>Se aplican las leyes de la República Argentina. Cualquier controversia se tramitará ante la jurisdicción que corresponda conforme a las normas imperativas aplicables, sin afectar derechos irrenunciables de usuarios o consumidores.</p></section>
  </LegalPage>;
}
