"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { LaboratoryManagementRecord, loadLaboratoryModule, saveLaboratoryRecord } from "../lib/laboratory-management-data";

type AnalysisLine = { id: string; analysisId: string; analysisQuery: string; quantity: number };
const lineId = () => Math.random().toString(36).slice(2, 8);
const money = (value: unknown) => `$ ${Number(value || 0).toLocaleString("es-AR")}`;
const today = () => new Date().toISOString().slice(0, 10);
const QUICK_SPECS = [
  { label: "BPA", code: "BPA" }, { label: "TRICHO + CAMPY", words: ["trichomon", "campylobacter"] },
  { label: "BPA + T/C", words: ["brucelosis", "trichomon", "campylobacter"] }, { label: "T/C + PCR", words: ["trichomon", "campylobacter", "pcr"] },
  { label: "AIE", code: "AIE" }, { label: "LEUCOSIS", code: "LEUCOSIS" }, { label: "PAL", code: "FAS" },
];

export default function LaboratorySampleIntakePanel({ uid }: { uid: string }) {
  const [samples, setSamples] = useState<LaboratoryManagementRecord[]>([]);
  const [prices, setPrices] = useState<LaboratoryManagementRecord[]>([]);
  const [vets, setVets] = useState<LaboratoryManagementRecord[]>([]);
  const [clients, setClients] = useState<LaboratoryManagementRecord[]>([]);
  const [lines, setLines] = useState<AnalysisLine[]>([{ id: lineId(), analysisId: "", analysisQuery: "", quantity: 1 }]);
  const [clientName, setClientName] = useState("");
  const [vetName, setVetName] = useState("");
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([loadLaboratoryModule(uid, "samples"), loadLaboratoryModule(uid, "prices"), loadLaboratoryModule(uid, "veterinarians"), loadLaboratoryModule(uid, "clients")]).then(([sampleRows, priceRows, vetRows, clientRows]) => { setSamples(sampleRows); setPrices(priceRows.filter((item) => item.status === "Activo")); setVets(vetRows); setClients(clientRows); }); }, [uid]);
  const protocol = `LAB-${new Date().getFullYear()}-${String(samples.length + 1).padStart(5, "0")}`;
  const quick = useMemo(() => QUICK_SPECS.map((spec) => ({ label: spec.label, item: prices.find((item) => spec.code ? String(item.code).toUpperCase() === spec.code : spec.words?.every((word) => `${item.name} ${item.code}`.toLowerCase().includes(word))) })).filter((entry) => entry.item), [prices]);
  const detail = lines.map((line) => ({ ...line, item: prices.find((item) => item.id === line.analysisId), subtotal: Number(prices.find((item) => item.id === line.analysisId)?.price || 0) * Number(line.quantity || 0) }));
  const totalSamples = lines.reduce((total, line) => total + Number(line.quantity || 0), 0);
  const total = detail.reduce((sum, line) => sum + line.subtotal, 0);
  const selectedClient = clients.find((item) => String(item.name).toLowerCase() === clientName.toLowerCase() || String(item.renspa || "").toLowerCase() === clientName.toLowerCase());
  function selectQuick(itemId: string) { const item = prices.find((price) => price.id === itemId); setLines([{ id: lineId(), analysisId: itemId, analysisQuery: String(item?.name || ""), quantity: 1 }]); }
  function updateLine(id: string, patch: Partial<AnalysisLine>) { setLines((current) => current.map((line) => line.id === id ? { ...line, ...patch } : line)); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!vetName || !clientName || detail.some((line) => !line.item)) { setMessage("Completá veterinario, productor/cliente y todos los análisis."); return; }
    setSaving(true); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); const stamp = new Date().toISOString();
    const record = { id: `sample-${Date.now()}`, protocol, date: form.date || today(), veterinarian: vetName, client: selectedClient?.name || clientName, species: form.species, renspa: selectedClient?.renspa || (/^\d{2}\.\d{3}/.test(clientName) ? clientName : ""), establishment: form.establishment, locality: form.locality, sampleType: form.sampleType, quantity: totalSamples, analyses: JSON.stringify(detail.map((line) => ({ id: line.item?.id, name: line.item?.name, quantity: line.quantity, unitPrice: line.item?.price, subtotal: line.subtotal }))), estimatedTotal: total, observations: form.observations, condition: "Aceptada", status: "Recibida", createdAt: stamp, updatedAt: stamp } as LaboratoryManagementRecord;
    await saveLaboratoryRecord(uid, "samples", record); setSamples((current) => [record, ...current]); setLines([{ id: lineId(), analysisId: "", analysisQuery: "", quantity: 1 }]); setVetName(""); setClientName(""); event.currentTarget.reset(); setMessage(`${protocol} guardado correctamente con ${totalSamples} muestras.`); setSaving(false);
  }
  return <><header className="topbar module-topbar laboratory-management-header"><div><span className="eyebrow">OPERACIÓN</span><h1>Ingreso de muestras</h1><p>Recepción rápida vinculada con veterinarios, productores y lista de precios.</p></div></header>{message && <div className="laboratory-message success">{message}<button onClick={() => setMessage("")}>×</button></div>}
    <section className="lab-quick-section"><div><h2>Accesos rápidos</h2><span>Diagnósticos o combinaciones usadas diariamente</span></div><div className="lab-quick-grid">{quick.map(({ label, item }, index) => <button className={index === 0 ? "selected" : ""} key={label} onClick={() => selectQuick(item!.id)}><b>{label}</b><small>{String(item!.name)}</small></button>)}<button onClick={() => setMessage("Los accesos se generan desde las combinaciones activas de la Lista de precios.")}><b>＋ Crear acceso</b><small>Nueva combinación</small></button></div></section>
    <form className="panel lab-intake-form" onSubmit={submit}><div className="lab-intake-title"><h2>Nuevo ingreso</h2><span>Protocolo automático: #{protocol}</span></div><div className="lab-intake-grid"><label>Veterinario<input list="lab-vets" value={vetName} onChange={(event) => setVetName(event.target.value)} placeholder="Escribí para buscar veterinario" required /><datalist id="lab-vets">{vets.map((item) => <option key={item.id} value={String(item.name)} />)}</datalist></label><label>Especie<select name="species" defaultValue="Bovino"><option>Bovino</option><option>Equino</option><option>Ovino</option><option>Porcino</option><option>Canino</option><option>Felino</option><option>Otra</option></select></label><label>Cantidad total de muestras<input value={totalSamples} readOnly /></label><label className="wide">RENSPA / Cliente / Productor<input list="lab-clients" value={clientName} onChange={(event) => setClientName(event.target.value)} placeholder="Escribí RENSPA o nombre del productor" required /><datalist id="lab-clients">{clients.flatMap((item) => [<option key={`${item.id}-name`} value={String(item.name)}>{String(item.renspa || "")}</option>, ...(item.renspa ? [<option key={`${item.id}-renspa`} value={String(item.renspa)}>{String(item.name)}</option>] : [])])}</datalist></label><label>Productor<input value={String(selectedClient?.name || "")} readOnly placeholder="Se completa con la búsqueda" /></label><label>Establecimiento<input name="establishment" placeholder="Nombre del establecimiento" /></label><label>Localidad<input name="locality" placeholder="Localidad" /></label><label>Fecha de ingreso<input name="date" type="date" defaultValue={today()} /></label><label>Tipo de muestra<input name="sampleType" placeholder="Sangre, suero, raspaje…" /></label></div>
      <section className="lab-requested-analyses"><div><h2>Análisis solicitados</h2><span>Vinculados con lista de precios</span></div>{lines.map((line) => { const item = prices.find((price) => price.id === line.analysisId); return <div className="lab-analysis-line" key={line.id}><label>Análisis<input list="lab-analysis-list" value={line.analysisQuery} onChange={(event) => updateLine(line.id, { analysisQuery: event.target.value, analysisId: prices.find((price) => String(price.name).toLowerCase() === event.target.value.toLowerCase())?.id || "" })} placeholder="Escribí para buscar análisis" required /></label><label>Cantidad<input type="number" min="1" value={line.quantity} onChange={(event) => updateLine(line.id, { quantity: Number(event.target.value) })} /></label><label>Precio unitario<input value={money(item?.price)} readOnly /></label><button type="button" onClick={() => setLines((current) => current.length === 1 ? current : current.filter((row) => row.id !== line.id))}>×</button></div>; })}<datalist id="lab-analysis-list">{prices.map((price) => <option key={price.id} value={String(price.name)}>{money(price.price)}</option>)}</datalist><button type="button" onClick={() => setLines((current) => [...current, { id: lineId(), analysisId: "", analysisQuery: "", quantity: 1 }])}>＋ Agregar análisis</button>
        <div className="lab-intake-summary"><div><b>Resumen estimado</b><small>Calculado según lista de precios vigente</small></div><section>{detail.filter((line) => line.item).map((line) => <article key={line.id}><span>{String(line.item?.name)} × {line.quantity}</span><strong>{money(line.subtotal)}</strong></article>)}<article><span>Total muestras</span><strong>{totalSamples}</strong></article><article className="total"><span>Total estimado</span><strong>{money(total)}</strong></article></section></div>
      </section><label className="lab-observations">Observaciones internas<textarea name="observations" placeholder="Muestras refrigeradas, derivar PCR, revisar identificación, etc." /></label><footer><button type="reset">Cancelar</button><button className="primary" disabled={saving}>{saving ? "Guardando…" : "Guardar ingreso"}</button></footer></form></>;
}
